"""empty message

Revision ID: 9528a12c20f9
Revises: bc24cbb8b201
Create Date: 2025-09-22 10:54:55.588047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9528a12c20f9'
down_revision = 'bc24cbb8b201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
