"""Temporarily allow duplicate emails for testing

Revision ID: af7ab1b6cd9b
Revises: b284e5719174
Create Date: 2025-09-18 17:22:43.448363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7ab1b6cd9b'
down_revision = 'b284e5719174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###
