"""Initial migration

Revision ID: b284e5719174
Revises: 
Create Date: 2025-09-17 12:24:41.885662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b284e5719174'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_answer_question_id_question', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), server_default=sa.text('1'), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_question_category_id_category'), 'category', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_category_id_category'), type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_question_id_question'), type_='foreignkey')
        batch_op.create_foreign_key('fk_answer_question_id_question', 'question', ['question_id'], ['id'])

    # ### end Alembic commands ###
